name: Container Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Containerfile'
      - '.github/workflows/container-image.yml'
      - 'files/**'
  schedule:
    - cron: '43 20 * * *'
concurrency:
  group: container-image-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  coreos-version-check:
    name: check if a newer version of CoreOS is available
    runs-on: ubuntu-24.04
    outputs:
      newer-version-available: ${{ steps.check-version.outputs.newer-version-available }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: check-version
        name: check if a newer version is available
        shell: bash
        run: .github/scripts/check-coreos-version.sh

  build-image:
    name: build fedora-coreos-bootc image
    needs: coreos-version-check
    if: needs.coreos-version-check.outputs.newer-version-available == 'true'
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set image variables
        run: |
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "LOCAL_IMAGE=${GITHUB_REPOSITORY,,}:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build container
        run: |
          set -euo pipefail
          podman build \
            --file=Containerfile \
            --tag="$LOCAL_IMAGE" \
            "$GITHUB_WORKSPACE"

      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin

      - name: Push container
        run: |
          set -euo pipefail
          podman push --format oci "$LOCAL_IMAGE" "$IMAGE:stable"
          podman push --format oci "$LOCAL_IMAGE" "$IMAGE:${SHORT_SHA}"
