name: Container Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Containerfile'
      - '.github/workflows/container-image.yml'
      - 'files/**'
  schedule:
    - cron: '43 20 * * *'
concurrency:
  group: container-image-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  coreos-version-check:
    name: check if a newer version of CoreOS is available
    runs-on: ubuntu-24.04
    outputs:
      newer-version-available: ${{ steps.coreos-version-check.outputs.newer-version-available }}
    steps:
      - id: check-version
        name: check if a newer version is available
        shell: bash
        run: |
          set -euo pipefail
          
          NAME="kuba86/fedora-coreos-bootc"
          TAG="stable"
          
          TOKEN="$(curl -fsSL "https://ghcr.io/token?service=ghcr.io&scope=repository:${NAME}:pull" \
            | jq -r '.token')"
          
          MANIFEST_JSON="$(curl -fsSL \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/${NAME}/manifests/${TAG}")"
          
          CONFIG_DIGEST="$(jq -r '.config.digest' <<<"$MANIFEST_JSON")"
          
          GHCRIO_DATETIME=$(curl -fsSL -H "Authorization: Bearer ${TOKEN}" \
            "https://ghcr.io/v2/${NAME}/blobs/${CONFIG_DIGEST}" | jq -r '.created')
          
          COREOS_DATETIME=$( curl -fsSL https://builds.coreos.fedoraproject.org/streams/stable.json \
            | jq -r '.metadata["last-modified"]')
          
          GHCRIO_TIMESTAMP=$(date -d "$GHCRIO_DATETIME" +%s)
          COREOS_TIMESTAMP=$(date -d "$COREOS_DATETIME" +%s)
          
          if [[ "$GHCRIO_TIMESTAMP" -lt "$COREOS_TIMESTAMP" ]]; then
            echo "GHCRIO is newer than COREOS, no need to rebuild"
            echo "newer-version-available=false" >> "$GITHUB_OUTPUT"
          else
            echo "GHCRIO is older than COREOS, will rebuild"
            echo "newer-version-available=true" >> "$GITHUB_OUTPUT"
          fi

  build-image:
    name: build fedora-coreos-bootc image
    needs: coreos-version-check
    if: needs.coreos-version-check.outputs.newer-version-available == 'true'
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set image variables
        run: |
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "LOCAL_IMAGE=${GITHUB_REPOSITORY,,}:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build container
        run: |
          set -euo pipefail
          podman build \
            --file=Containerfile \
            --tag="$LOCAL_IMAGE" \
            "$GITHUB_WORKSPACE"

      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin

      - name: Push container
        run: |
          set -euo pipefail
          podman push --format oci "$LOCAL_IMAGE" "$IMAGE:stable"
          podman push --format oci "$LOCAL_IMAGE" "$IMAGE:${SHORT_SHA}"
